/**
 * Static data for the /examples page.
 * Auto-generated by scripts/generate-examples.mjs — do not edit manually.
 * Last updated: 2026-04-03
 */
export const EXAMPLES = [
  {
    slug: 'irve-bornes-recharge',
    title: 'Electric Vehicle Charging Stations',
    source: 'data.gouv.fr',
    sourceUrl: 'https://www.data.gouv.fr/fr/datasets/irve-statique-engie-vianeo/',
    description:
      'French EV charging station network — 40 columns covering location, operator, connector types, power output, and accessibility across 200 stations.',
    rows: 200,
    columns: 40,
    sections: 4,
    imageSrc: '/examples/irve-bornes-recharge/overview.webp',
    imageSrcSet:
      '/examples/irve-bornes-recharge/overview.webp 1x, /examples/irve-bornes-recharge/overview@2x.webp 2x',
    imageAlt: 'PDF generated from Electric Vehicle Charging Stations data by fitforpdf — 40 columns split into 4 sections',
    pdfHref: '/examples/irve-bornes-recharge/output.pdf',
  },
  {
    slug: 'elections-europeennes-2024',
    title: 'European Election Results 2024',
    source: 'data.gouv.fr',
    sourceUrl: 'https://www.data.gouv.fr/fr/datasets/resultats-elections-europeennes-2024/',
    description:
      '2024 European Parliament election results — 50 columns with votes per party, turnout, abstention rates, and blank/null ballots across 200 municipalities.',
    rows: 200,
    columns: 50,
    sections: 4,
    imageSrc: '/examples/elections-europeennes-2024/overview.webp',
    imageSrcSet:
      '/examples/elections-europeennes-2024/overview.webp 1x, /examples/elections-europeennes-2024/overview@2x.webp 2x',
    imageAlt: 'PDF generated from European Election Results 2024 data by fitforpdf — 50 columns split into 4 sections',
    pdfHref: '/examples/elections-europeennes-2024/output.pdf',
  },
  {
    slug: 'annuaire-etablissements-scolaires',
    title: 'School Directory (Orléans Métropole)',
    source: 'data.gouv.fr',
    sourceUrl: 'https://www.data.gouv.fr/fr/datasets/annuaire-des-etablissements-scolaires-orleans-metropole/',
    description:
      'School directory for Orléans metropolitan area — 50 columns including school type, status, address, academic zone, and geographic coordinates across 265 establishments.',
    rows: 265,
    columns: 50,
    sections: 4,
    imageSrc: '/examples/annuaire-etablissements-scolaires/overview.webp',
    imageSrcSet:
      '/examples/annuaire-etablissements-scolaires/overview.webp 1x, /examples/annuaire-etablissements-scolaires/overview@2x.webp 2x',
    imageAlt: 'PDF generated from School Directory (Orléans Métropole) data by fitforpdf — 50 columns split into 4 sections',
    pdfHref: '/examples/annuaire-etablissements-scolaires/output.pdf',
  },
];
